name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild build test -destination ‘name=iPhone 11’ -scheme 'Throne’
