name: Swift

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild clean test -scheme "Throne - Develop" -destination "platform=iOS Simulator,name=iPhone 11"
