name: Swift

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: xcodebuild test -scheme "Throne - Production" -destination "name=iPhone 11"
